### ISSUE TITLE
Data-Proofing

### ISSUE THREAD

**Issue by hereismyname** [SSW-DataLab/sswdlHelpR#10]
https://github.com/dataproofer/Dataproofer

This is a long-term goal, and we should bring it up with the lab at large before any work is done. I saw this on FlowingData a while ago, and it seemed like these basic routines could be ported to R as a single function, or set of functions. We don't need to copy their exact implementations, but they could be represented as needed in R. You and I have talked about writing code that "intelligently" understands data quality, without necessitating a lot of human instruction-- this might be a place to start.

**Comment by ClaytonJY** [comment]
Per slack discussion with @beperron, we won't be addressing this.
