### ISSUE TITLE
Utility functions to check for aberrant values

### ISSUE THREAD

**Issue by hereismyname** [SSW-DataLab/sswdlHelpR#4]
[I have a few helper functions that I've found myself defining fairly frequently.](https://gist.github.com/hereismyname/df70dadd3be5a10ddc46551670d5acb2)

They're only wrapper functions, but are useful to check the results of a column or vector you've created. I'm not sure what a good file-name should be for them, but I think `sumNA()` and `anyNeg()` might be useful.

**Comment by ClaytonJY** [comment]
@hereismyname I'm a little hesitant to green-light aliases for literal one-line functions. I think it's great to have those in a personal file for doing quick unrecorded data analyses, but I think wrapping these in a function actually makes it less obvious what's happening in a recorded analysis workflow.

What if we expanded them to apply to `data.frame`'s / `tbl_df`'s and give some nice output, perhaps combining them into some larger functions? We'd have to talk more about specifics, but I could see value in having some "datalab-standard" convenience functions that combine a bunch of routine checks we tend to do on datasets.

**Comment by ClaytonJY** [comment]
After speaking with @hereismyname, we'll be making a more detailed function which creates a sort of meta-summary about an input data.frame. Andrew has been using such a function in his work and has handed his code to me to fold into this package.

**Comment by ClaytonJY** [comment]
Addressed in #6.
